SUB_MODEL := VM670

# Board properties
TARGET_BOARD_PLATFORM := msm7k
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv6-vfp
TARGET_CPU_ABI := armeabi-v6l
TARGET_CPU_ABI2 := armeabi
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200

# Target properties
TARGET_OTA_ASSERT_DEVICE := thunderc

# Target information
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_BOOTLOADER_BOARD_NAME := thunderc
TARGET_OTA_ASSERT_DEVICE := thunderc,VM670

#BOOT AND BOOTLOADER
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Camera
USE_CAMERA_STUB := false
#BOARD_USE_FROYO_LIBCAMERA := true
BUILD_OLD_LIBCAMERA:= true

# Graphics
BOARD_USES_ADRENO_200 := true
BOARD_AVOID_DRAW_TEXTURE_EXTENSION := true
TARGET_LIBAGL_USE_GRALLOC_COPYBITS := true
TARGET_DO_NOT_SETS_CAN_DRAW := true
TARGET_SF_NEEDS_REAL_DIMENSIONS := true
BOARD_NO_RGBX_8888 := true
BOARD_EGL_CFG := device/lge/thunderc/files/lib/egl/egl.cfg
BOARD_HAS_LIMITED_EGL := true
BOARD_USE_NASTY_PTHREAD_CREATE_HACK := true
TARGET_USES_16BPPSURFACE_FOR_OPAQUE := true

TARGET_PROVIDES_INIT_TARGET_RC := true

# Sensors
TARGET_USES_OLD_LIBSENSORS_HAL := true
BOARD_VENDOR_USE_AKMD := akm8973

# Touchscreen
BOARD_USE_LEGACY_TOUCHSCREEN := true

# QCOM
BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_QCOM_LIBS := true
COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE
BOARD_USES_QCOM_LIBRPC := true
BOARD_USES_QCOM_LEGACY := true

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true
BOARD_FORCE_STATIC_A2DP := true

# GPS
BOARD_USES_GPSSHIM := true
BOARD_GPS_NEEDS_XTRA := true
BOARD_GPS_LIBRARIES := libloc

# USB mass storage
BOARD_USE_USB_MASS_STORAGE_SWITCH := true
BOARD_CUSTOM_USB_CONTROLLER := ../../device/lge/thunderc/netd/UsbController.cpp
BOARD_UMS_LUNFILE := /sys/devices/platform/msm_hsusb/gadget/lun0/file
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/usb_mass_storage/lun0/file

# WiFi related defines
WPA_SUPPLICANT_VERSION := VER_0_5_X
BOARD_WPA_SUPPLICANT_DRIVER := WEXT
BOARD_WLAN_DEVICE := bcm4325
BOARD_WIRELESS_CHIP := bcm4325
WIFI_DRIVER_MODULE_PATH := "/system/lib/modules/wireless.ko"
WIFI_DRIVER_MODULE_ARG := "firmware_path=/system/etc/wl/rtecdc.bin nvram_path=/system/etc/wl/nvram.txt"
WIFI_DRIVER_MODULE_NAME := wireless
WIFI_PRE_LOADER := "qcom_sdio_init"
WIFI_POST_UNLOADER := "qcom_sdio_deinit"
WIFI_DRIVER_FW_STA_PATH := "/system/etc/wl/rtecdc.bin"
WIFI_DRIVER_FW_AP_PATH := "/system/etc/wl/rtecdc-apsta.bin"
WIFI_DRIVER_HAS_LGE_SOFTAP := true

# Kernel
TARGET_PREBUILT_KERNEL := device/lge/thunderc/files/kernel/$(SUB_MODEL)
BOARD_KERNEL_CMDLINE := mem=477M console=ttyMSM2,115200n8 androidboot.hardware=thunderc uart_console=disable recovery=off lge.rev=10
BOARD_KERNEL_BASE := 0x12200000
BOARD_PAGE_SIZE := 0x00000800

# Appropriate defaults?
BOARD_FLASH_BLOCK_SIZE := 131072

# Optimus S
ifeq ($(SUB_MODEL),LS670)
    BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00700000
    BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00700000
    BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x09e80000
    BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x0a4e0000
endif

# Optimus V
ifeq ($(SUB_MODEL),VM670)
    BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00700000
    BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00700000
    BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x0a480000
    BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x0b2e0000
endif

# Optimus M
ifeq ($(SUB_MODEL),MS690)
    BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00500000
    BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00500000
    BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x0bd00000
    BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x0c900000
endif

# Optimus C
ifeq ($(SUB_MODEL),LW690)
    BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00500000
    BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00500000
    BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x0bd00000
    BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x0c900000
endif

# Optimus Vortex
ifeq ($(SUB_MODEL),VS660)
    BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00500000
    BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00500000
    BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x0bb00000
    BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x0b8e0000
endif

#BOARD_HAS_NO_SELECT_BUTTON := true

TARGET_USES_OVERLAY := true

# Browser
WITH_JIT := false
ENABLE_JSC_JIT := false
JS_ENGINE := v8

# Audio
TARGET_PROVIDES_SURFACEFLINGER := true
BUILD_WITH_FULL_STAGEFRIGHT := true
TARGET_PROVIDES_LIBAUDIO := true
BOARD_USES_AUDIO_LEGACY := true

# RIL
# TARGET_PROVIDES_LIBRIL = vendor/lge/thunderc/proprietary/system/lib/libril-qc-1.so

# FM radio
#BOARD_HAVE_FM_RADIO := true
#BOARD_GLOBAL_CFLAGS += -DHAVE_FM_RADIO
#TARGET_SF_NEEDS_REAL_DIMENSIONS := true

# Charging while powered off
BOARD_GLOBAL_CFLAGS += -DCHARGERMODE_CMDLINE_NAME='"lge.reboot"' -DCHARGERMODE_CMDLINE_VALUE='"pwroff"'

#ICS settings
DISABLE_DEXPREOPT := true
BOARD_NO_PAGE_FLIPPING := true
USE_OPENGL_RENDERER := false
BOARD_NO_PAGE_FLIPPING := true
COPYBIT_MSM7K := true
TARGET_FORCE_CPU_UPLOAD := true
COMMON_GLOBAL_CFLAGS += -DTARGET_MSM7x27 -DNO_RGBX_8888 #-DQCOM_HARDWARE
COMMON_GLOBAL_CFLAGS += -DMISSING_EGL_EXTERNAL_IMAGE -DMISSING_GRALLOC_BUFFERS
COMMON_GLOBAL_CFLAGS += -DMISSING_EGL_PIXEL_FORMAT_YV12
COMMON_GLOBAL_CFLAGS += -DBOARD_GL_OES_EGL_IMG_EXTERNAL_HACK
COMMON_GLOBAL_CFLAGS += -D_INTERNAL_BINDER_PARCEL_ -DUSE_LGE_ALS_DUMMY
TARGET_GLOBAL_CFLAGS += -mfpu=vfp -mfloat-abi=softfp -Os
TARGET_GLOBAL_CPPFLAGS += -mfpu=vfp -mfloat-abi=softfp -Os
